sudo: required

language: python
python:
  - 3.6

matrix:
  include:
    - compiler: gcc
      before_script:
        - python3 -m pip install numpy sphinx
        - git clone https://github.com/plures/ndtypes.git
        - cd ndtypes
        - python3 setup.py install --local=../python
        - cd ..
      script:
        - ./configure
        - make check
        - python3 setup.py module
        - python3 setup.py test
        - python3 setup.py doctest

    - compiler: gcc
      before_script:
        - sudo apt-get install -y valgrind
        - git clone https://github.com/plures/ndtypes.git
        - cd ndtypes
        - python3 setup.py install --local=../python
        - cd ..
      script:
        - ./configure
        - make memcheck
        - python3 setup.py module
        - python3 setup.py test

    - compiler: clang
      before_script:
        - git clone https://github.com/plures/ndtypes.git
        - export CC=clang
        - cd ndtypes
        - python3 setup.py install --local=../python
        - cd ..
      script:
        - ./configure
        - make check
        - python3 setup.py module
        - python3 setup.py test

    - language: objective-c
      os: osx
      compiler: clang
      before_install:
        - brew install python3
      before_script:
        - git clone https://github.com/plures/ndtypes.git
        - export CC=clang
        - cd ndtypes
        - python3 setup.py install --local=../python
        - cd ..
      script:
        - ./configure
        - make check
        - python3 setup.py module
        - python3 setup.py test

    - compiler: gcc
      before_script:
        - git clone https://github.com/plures/ndtypes.git
        - cd ndtypes
        - python3 setup.py install --local=../python
        - cd ..
      script:
        - python3 setup.py build
        - python3 setup.py test

    - compiler: conda
      install:
        - cd ..
        - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh
        - bash Miniconda3-latest-Linux-x86_64.sh -b
        - export PATH=$HOME/miniconda3/bin:$PATH
        - conda update --yes conda
        - conda install --yes conda-build=3.3.0
        - conda install --yes anaconda-client
        - conda install --yes -c xnd/label/dev ndtypes
      script:
        - cd xnd
        - git fetch --unshallow
        - conda build .conda/libxnd -c xnd/label/dev
        - conda build .conda/xnd -c xnd/label/dev

    - language: objective-c
      os: osx
      compiler: conda
      install:
        - cd ..
        - wget https://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh
        - bash Miniconda3-latest-MacOSX-x86_64.sh -b
        - export PATH=$HOME/miniconda3/bin:$PATH
        - export CC=clang
        - conda update --yes conda
        - conda install --yes conda-build=3.3.0
        - conda install --yes anaconda-client
        - conda install --yes -c xnd/label/dev ndtypes
      script:
        - cd xnd
        - git fetch --unshallow
        - conda build .conda/libxnd -c xnd/label/dev
        - conda build .conda/xnd -c xnd/label/dev
